apiVersion: apps/v1
kind: Deployment
metadata:
  name: havenf-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: havenf
  template:
    metadata:
      labels:
        app: havenf
    spec:
      containers:
      - name: havenf
        image: bonnil1/haven-frontend:6.0
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 3000 # 80: apache listening on port 80 in container OR 3000 for local and nginx

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: havenf
  ports:
  - port: 3000 # http://frontend:3000
    targetPort: 3000 # 80: where apache is serving react app OR 3000 for local and nginx
  #type: LoadBalancer
    nodePort: 31559
  type: NodePort